### PR TITLE
use updated nginx

### PR DESCRIPTION
**Pull request by henrikx**
Updates dockerfile to always use the latest nginx image.

It builds: https://hub.docker.com/r/henrikx/nginx-subs-filter

### CODE REVIEW

**Comment by henrikx** [comment]
merge as one commit as most of them are minor edits.

**Comment by cdue** [comment]
Hi @henrikx,
Thanks for your Pull Request 🙏
I never took the time to do it, but as mentioned on comments on top of the Dockerfile, I would have liked to use the stable nginx tag rather than the mainline or latest, in order to avoid potential buggy new feature just added in the latest tag. What do you think? If the 1.18.0 (stable) version is enough for your needs, can you update your PR this way?

**Comment by henrikx** [comment]
Hi. I have made a commit to reflect that :)

**Comment by cdue** [comment]
> Hi. I have made a commit to reflect that :)

Perfect, thank you.
I just tried to build the image and everything looks good 👍

**Pull request merged**
